// src/components/Login.svelte
<script>
  import Spinner from './Spinner.svelte';
  import { session } from '../stores';
  import { login, getMe } from '../services/RedditService';

  let username;
  let password;
  let error;
  let loading = false;

  async function handleSubmit() {
    if (username && (username = username.trim()) &&
        password && (password = password.trim())) {
      loading = true;
      try {
        await login(username, password);
        const user = await getMe();
        session.update(value => {
          value.username = user.username;
          value.email = user.email;
          value.isLoggedIn = true;
          return value;
        });
      } catch (err) {
        error = err.message;
      }
      loading = false;
    }
  }
</script>

{#if loading}
  <Spinner />
{:else}
  <form class="login" on:submit|preventDefault={handleSubmit}>
    <p class="login-text">Please log in to continue.</p>
    {#if error}
      <p class="error-text">{error}</p>
    {/if}
    <input class="username-input" bind:value={username} name="username" placeholder="Username" type="text" required>
    <input class="password-input" bind:value={password} name="password" placeholder="Password" type="password" required>
    <button class="login-btn" type="submit">Login</button>
  </form>
{/if}

<style>
  .login {
    display: grid;
    grid-gap: 12px;
    grid-template-columns: repeat(3, 1fr);
  }

  .login-text, .error-text {
    text-align: center;
  }

  .username-input, .password-input, .login-btn {
    grid-column: 2 / 2;
  }

  .login-text, .error-text {
    grid-column: 1 / 4;
  }

  .error-text {
    color: red;
  }
</style>

// src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';

import { RedditService } from '../services/reddit.service';
import { StorageService } from '../services/storage.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  private readonly INVALID_LOGIN_ERROR_MESSAGE = 'Invalid username or password';
  username: string;
  password: string;
  errorMessage: string;

  constructor(
    public redditService: RedditService,
    public storageService: StorageService
  ) { }

  ngOnInit() {
    this.storageService.message = 'Please log in to continue.';
  }

  async login() {
    if (this.username && (this.username = this.username.trim()) &&
        this.password && (this.password = this.password.trim())) {
      try {
        return await this.redditService.login(this.username, this.password);
      } catch { }
    }

    this.errorMessage = this.INVALID_LOGIN_ERROR_MESSAGE;
  }
}

<form *ngIf="!redditService.loading" (submit)="login()">
  <div class="form-error" *ngIf="errorMessage">{{errorMessage}}</div>
  <input class="form-control" name="username" type="text" placeholder="Username" [(ngModel)]="username" required>
  <input class="form-control" name="password" type="password" placeholder="Password" [(ngModel)]="password" required>
  <button class="btn btn-primary form-btn" type="submit">Login</button>
</form>
